### ISSUE TITLE
细节改进

### ISSUE THREAD

**Issue by exquisa** [gsdlone/gship#22]
- 数据库注册界面两个密码不可明文显示，加验证

- 培养层次提示改为 硕士/博士
![image](https://user-images.githubusercontent.com/36413422/36945876-32f33ccc-1fef-11e8-88d0-5a73d35fa400.png)

- 在未勾选我是共同一作作者情况下，隐藏后面两行内容，并赋默认值
![image](https://user-images.githubusercontent.com/36413422/36945895-86812318-1fef-11e8-954f-c401d73773eb.png)

**Comment by xinyuxinyu** [comment]
Done
