### ISSUE TITLE
Improvement: details enhancement.

### ISSUE THREAD

**Issue by gsdlone** [gsdlone/gship#3]
学生资料页内容修改

学生资料需要包括：姓名，ARP号，手机号，邮箱，部门，专业，学生类别，培养层次，指导教师，入学年份。

目前我们有：
姓名，手机/电话，组别，邮箱，攻读专业，攻读方式，指导教师，入学年份

需要增加：ARP号，学生类别（本所生，联培生，课题组自招生）

需要改名：组别 -> 部门，攻读方式 -> 培养层次

**Comment by exquisa** [comment]
测试一下功能 @xinyuxinyu

**Comment by xinyuxinyu** [comment]
学生资料页信息齐全
