### ISSUE TITLE
Feature: scholarship restrictions

### ISSUE THREAD

**Issue by gsdlone** [gsdlone/gship#4]
- [x] 参评奖学金的发表成果须以苏州纳米所为第一单位，加工平台奖学金和华灿奖学金可放宽至通讯作者为纳米所导师，第一单位不做要求；
- [x] 参评奖学金的发表成果中，研究生第一作者或第一发明人采取上述计分；
- [x] 成果中研究生为第二作者且导师为第一作者的成果视同研究生为第一作者；
共同一作的成果，排名第一的影响因子和分数计50%，其他作者均分另外50%。
- [x] 同一级别或同一奖项奖学金申请，科研成果不得重复使用。
- [x] 国家奖学金硕士阶段和博士阶段可各申请一次，但成果不得重复使用。
- [x] 联培生和课题组自招生只能参评所级奖学金

/cc @xinyuxinyu

**Comment by exquisa** [comment]
### Restrictions
- 同一级别~~或同一奖项~~奖学金申请，科研成果不得重复使用（注：同一级别限制包含同一奖项）
- 国家奖学金硕士阶段和博士阶段可各申请一次，但成果不得重复使用
- 联培生和课题组自招生只能参评所级奖学金
- 参评奖学金的发表成果须以苏州纳米所为第一单位，加工平台奖学金和华灿奖学金可放宽至通讯作者为纳米所导师，第一单位不做要求

### 目前需要填报系统的奖学金包括：
- **国家级：**
1. 国家奖学金
- **院级：**
1. 院长奖
2. 南京分院伍宜孙奖学金
3. 朱李月华奖学金
- **校级：**
1. 光华奖学金
2. 牛津仪器奖学金
- **所级：**
1. 加工平台奖学金
 2. 华灿光电奖学金

**Comment by xinyuxinyu** [comment]
Done.
